# El metodo de k-means

In [1]:
import numpy as np


In [4]:
data=np.random.random(90).reshape(30,3)
data

array([[0.05734006, 0.98802053, 0.2930241 ],
       [0.08067502, 0.63344337, 0.56712799],
       [0.0882042 , 0.18238379, 0.78383874],
       [0.139744  , 0.21736086, 0.70899264],
       [0.49824798, 0.9792645 , 0.13335182],
       [0.56305299, 0.44386883, 0.1732493 ],
       [0.45122488, 0.24132193, 0.04331567],
       [0.94510683, 0.25599092, 0.90950983],
       [0.00731092, 0.97003667, 0.17729839],
       [0.10097069, 0.36655288, 0.30298455],
       [0.20935699, 0.7140942 , 0.77830633],
       [0.6220082 , 0.7722637 , 0.3754507 ],
       [0.33005504, 0.91576784, 0.80144856],
       [0.76649612, 0.21038285, 0.62036768],
       [0.5436347 , 0.32712001, 0.66007934],
       [0.29068359, 0.56348391, 0.87877528],
       [0.75067135, 0.75778986, 0.85532332],
       [0.3026943 , 0.65308433, 0.98143832],
       [0.7731089 , 0.42285877, 0.97160882],
       [0.95521729, 0.32229912, 0.38278199],
       [0.20464388, 0.11951918, 0.26660299],
       [0.63290408, 0.00562959, 0.64807502],
       [0.

In [7]:
c1=np.random.choice(range(len(data)))
c2=np.random.choice(range(len(data)))
clust_centers=np.vstack([data[c1],data[c2]])
#baricentros 
clust_centers


array([[0.0882042 , 0.18238379, 0.78383874],
       [0.05734006, 0.98802053, 0.2930241 ]])

In [8]:
from scipy.cluster.vq   import vq

In [10]:
vq(data,clust_centers)
#primera informacion a que claster pertenece
# segunda informacion distancia al baricentro

(array([1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 1, 0, 0, 0, 0, 0]),
 array([0.        , 0.44877882, 0.        , 0.09737394, 0.4690114 ,
        0.75245773, 0.8268205 , 0.8691912 , 0.12735295, 0.51507474,
        0.54536645, 0.61007808, 0.58145451, 0.69827405, 0.49364147,
        0.44186893, 0.88037771, 0.55372429, 0.74978681, 0.96547114,
        0.53389417, 0.58853359, 0.73051064, 0.50363907, 0.4306796 ,
        0.31921829, 0.4652299 , 0.67278957, 0.78416814, 0.37036444]))

In [11]:
from scipy.cluster.vq   import kmeans

In [13]:
kmeans(data,clust_centers)
#informacion de los baricentros

(array([[0.48931947, 0.33805066, 0.59979843],
        [0.19324656, 0.75409159, 0.45080409]]), 0.40664706980094406)

In [14]:
kmeans(data,2)

(array([[0.32512621, 0.73505747, 0.65140964],
        [0.43639261, 0.24614053, 0.43892471]]), 0.39473955698873564)

In [18]:
from rpy2.robjetcs import pandas2ri

ModuleNotFoundError: No module named 'rpy2'